name: Sql execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona un entorno'
        required: true
        default: 'DEV'
        options: 
          DEV: 'Desarrollo'
          QA: 'Control de calidad'
          STG: 'Preproducción'
  
jobs:
  determine_host_options:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get username
      id: get_username
      run: echo "::set-output name=username::${{ github.actor }}"
    
    - name: Associated app
      id: determine_app
      run: |
        username=${{ steps.get_username.outputs.username }}
        if [ "$username" == "Josep" ]; then
          echo "::set-output name=app::reviews"
        elif [ "$username" == "ruben" ]; then
          echo "::set-output name=app::Localsites"
        else
          echo "::set-output name=app::OtherApp"
    
    - name: Endpoint depending on user
      id: determine_host_options
      run: |
        app=${{ steps.determine_app.outputs.app }}
        user=${{ steps.get_username.outputs.username }}
        environment=${{ github.event.inputs.environment }}
        
        echo "Aplicación: $app"
        echo "Usuario: $user"
        echo "Entorno: $environment"
        echo "hosts: ${user}-${app}-${environment}, ${user}-${app}-${environment}"
