
name: Sql execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona un entorno'
        required: true
        default: 'DEV'
        type: choice
        options:
        - dev
        - qa
        - stg
 
      jira:
        description: 'Jira number'
        required: true
 
jobs:
  determine_host_options:
    runs-on: ubuntu-latest
   
    steps:
    - name: Get username
      id: get_username
      run: echo "username=${{ github.actor }}" >> "$GITHUB_OUTPUT"

    - name: Checkout
      uses: actions/checkout@v2.3.2
        
    - name: Run Config Check
      id: config-check
      run: |
        # Use your script/command to find and process config files
        username=${{ github.actor }}
        env=${{ inputs.environment }}
        jira=${{ inputs.jira }}
        echo $username
        echo $env
        echo $jira
        
        files=$(find configs/$username -name "*$env.conf")   
        
        for file in $files; do
          filename=$(basename -- "$file")
          db_name=${filename%-*}
          echo "Found config file: $file, DB name: $db_name"
        done
                     
    - name: psql_exec
      run: |
       #sudo apt install wget ca-certificates
       #wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
       #sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
       #sudo apt update
       #sudo apt install postgresql postgresql-contrib
