
name: Sql execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona un entorno'
        required: true
        default: 'DEV'
        type: choice
        options:
        - dev
        - qa
        - stg
 
      jira:
        description: 'Jira number'
        required: true
 
jobs:
  determine_host_options:
    runs-on: ubuntu-latest
    outputs:
     username: ${{ steps.get_username.outputs.username }}
     git_url: ${{ steps.config-check.outputs.git_url }}
     git_table_path: ${{ steps.config-check.outputs.git_table_path }}
     git_branch: ${{ steps.config-check.outputs.git_branch }}
     
    steps:
    - name: Get username
      id: get_username
      run: echo "username=${{ github.actor }}" >> "$GITHUB_OUTPUT"

    - name: psql_exec
      run: |
       sudo apt install wget ca-certificates
       wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
       sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
       sudo apt update
       sudo apt install postgresql postgresql-contrib

# Checkout repo local
    - name: Checkout
      uses: actions/checkout@v2.3.2
        
    - name: Run Config Check
      id: config-check
      run: |
        # Use your script/command to find and process config files
        username=${{ github.actor }}
        env=${{ inputs.environment }}
        jira=${{ inputs.jira }}
        
        files=$(find configs/$username -name "*$env.conf")   
        
        for file in $files; do
          source "$file"
        done
        echo $git_url >> "$GITHUB_OUTPUT"
        echo $git_table_path >> "$GITHUB_OUTPUT"
        echo $git_branch >> "$GITHUB_OUTPUT"

    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: ${{ github.$git_url }}
        token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
        path: ${{ github.$git_table_path }}

        echo "psql -X -U ${adminUser} -h ${host} ${DB} -f scripts/file.sql --echo-all -o /output/result.txt"
